# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14c3d1f024d8e971d6518fa00090432db0afa8ba402a1bccccff7aa22bbffec919503ece975f40613a1085cfb44643c5c1b014b4c39fb7207ae98efe8d61a3b9

test:
  secret_key_base: 3d5a40cec7ec945d7ae60acaf9e6e81ad0dc669ef5a81b832e5d4e99b270d58abe88e9dae00e1c23319bdbb2a2ec1021de32b7ebc9ffd3ff81390da4fd579e2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
